spring.application.name=DOSW-Library
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=edu.eci.dosw.tdd.controller
springdoc.pathsToMatch=/books/**,/loans/**,/users/**